### ISSUE TITLE
Identifying peer support / safety

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/tls-exported-authenticator#13]
Currently, this defines an API that can be used unilaterally by either side of a TLS connection.  However, the API is effectively useless if both sides don't support it.  Currently, it's left to the application layer to perform that negotiation (e.g. the setting defined for HTTP/2).  However, that application layer might not have visibility into the conditions into which it's safe to use this API (EMS or TLS 1.3).  If #12 is addressed by having the API fail in that case, the application layer would negotiate the use of this feature, then find the API unavailable at a later point.

It might be cleaner and more testable to have an explicit extension defined, even if there are no options to carry, with the security requirements placed around when the extension can be offered/accepted.  If the extension is successfully negotiated in the handshake, both sides can be confident that the API will be functional on both sides of the TLS connection.

**Comment by grittygrease** [comment]
I’m not sure adding a TLS extension is a good idea. The document recommends that the TLS library implements the API, but it could very well be implemented at a higher layer or even in a wrapper. Changing the wire format of the connection doesn’t help users of the API know whether EMS is supported, it’s the collection of negotiated properties that determines that.

Maybe describing an API in this document that states whether or not a connection is suitable for Exported Authenticators as negotiates would be sufficient.

**Comment by martinthomson** [comment]
For the record, I agree with @grittygrease.  Better to signal support for this at the application layer (where the messages are exchanged).
