### ISSUE TITLE
No API to retrieve the context of a request

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/tls-exported-authenticator#43]
In the HTTPbis meeting in Montreal, it was suggested that recipients of a `CERTIFICATE_REQUEST` frame should validate that the claimed Request-ID matched the `certificate_request_context` in the supplied authenticator request.  However, the document defines no API which would permit us to do that.

**Comment by grittygrease** [comment]
Shouldn't this be implemented at the HTTP layer using the "get context" API? This document is not prescriptive about the content of the crc except that it is unpredictable and unique.

**Comment by MikeBishop** [comment]
`get context` allows us to extract it from an authenticator, but doesn't allow performing the same operation on a request.

**Comment by grittygrease** [comment]
Good point. This should be a simple addition.

**Comment by grittygrease** [comment]
https://github.com/tlswg/tls-exported-authenticator/pull/45
