### ISSUE TITLE
Layout issues in API section

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/tls-exported-authenticator#44]
The definition of the "validate" API should presumably be bulleted like the other APIs, but is actually a series of asterisks in the body of the text.

**Comment by grittygrease** [comment]
I don't see this in the final document: https://www.ietf.org/id/draft-ietf-tls-exported-authenticator-08.txt 

Can you point it out to me?

**Comment by MikeBishop** [comment]
I don't see it in that version of the document either.  However, I see plenty there that's not in the GitHub version.  (For example, the fact that validate is Section 6.4, rather than part of Section 5.)  Do you perhaps have local changes you haven't pushed?

**Comment by grittygrease** [comment]
I checked out a fresh copy of the repo and am still not seeing these issues. Can you submit a PR?

**Comment by MikeBishop** [comment]
Ah, I see the problem -- the gh-pages version of the draft hasn't been built since January, and it's a problem that's been fixed since then.  No wonder there's such a large diff when I [compare](https://tools.ietf.org/rfcdiff?url1=https://tools.ietf.org/id/draft-ietf-tls-exported-authenticator.txt&url2=https://tlswg.github.io/tls-exported-authenticator/draft-ietf-tls-exported-authenticator.txt) the editor's copy and the official draft....
