### ISSUE TITLE
WGLC Issue: Russ

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls-exported-authenticator#62]
Section 4: I find this confusing:

    extensions:  The set of extensions allowed in the CertificateRequest
       structure are those defined in the TLS ExtensionType Values IANA
       registry containing CR in the TLS 1.3 column.  The extensions
       allowed in the ClientCertificateRequest are those containing CR in
       the TLS 1.3 column, along with the server_name [RFC6066]
       extension.

I think it means:

    extensions:  The set of extensions allowed in the CertificateRequest
       structure and the ClientCertificateRequest structure are those
       defined in the TLS ExtensionType Values IANA registry [cite]
       containing CR in the TLS 1.3 column.  In addition, the set of
       extensions in the ClientCertificateRequest structure MAY
       include the server_name [RFC6066] extension.

**Comment by grittygrease** [comment]
fixed in #65
