### ISSUE TITLE
Consider naming the server's CR ServerCertificateRequest

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-exported-authenticator#70]
This is a suggestion from @hugokraw. Given that we already refer to the client's CR as ClientCertificateRequest for clarity's sake, making a similar change for the server's CR seems quite reasonable.

**Comment by martinthomson** [comment]
For these messages that don't have a direction, I've used "client Certificate" or "server Certificate".  I don't see an issue with that, whereas a new CamelCaseName that doesn't match the grammar is confusing.

**Comment by chris-wood** [comment]
The messages themselves don't have a direction -- it's the name that assigns them a direction. Either way, all this issue is recommending is that we're consistent with how we choose that name. Both "client CertificateRequest" and "ClientCertificateRequest" work equally well for me.

**Comment by seanturner** [comment]
@grittygrease I suspect this is OBE and can be closed.
