### ISSUE TITLE
Don't include DTLS fields

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls-exported-authenticator#8]
Even if the protocol is DTLS, the message_seq, fragment_offset, and fragment_length fields aren't included.

**Comment by grittygrease** [comment]
Is it not clear from the text that the messages are the TLS 1.3 version of the messages?

**Comment by martinthomson** [comment]
It says TLS 1.3.  But the protocol can be used with DTLS (I assume), so there is the potential for confusion about whether to use the native formats for that variant or the TLS variants always.  Either would work, but only one choice is interoperable.

**Comment by grittygrease** [comment]
I don't think there is any ambiguity. We explicitly state that they are TLS 1.3 messages and point to the spec (even for TLS 1.2).
